# Generated by Django 6.0.3 on 2026-04-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.CharField(max_length=50, unique=True, verbose_name='Department ID')),
                ('name', models.CharField(max_length=100, verbose_name='Department Name')),
                ('head_of_department', models.CharField(max_length=100, verbose_name='Head of Department')),
                ('start_date', models.DateField(verbose_name='Department Start Date')),
                ('no_of_students', models.IntegerField(default=0, verbose_name='No of Students')),
            ],
        ),
    ]
