# Generated by Django 6.0.3 on 2026-03-28 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='tudent_id',
            new_name='student_id',
        ),
    ]
